### ISSUE TITLE
No debug symbols are available for prebuilt libchromiumcontent

### ISSUE THREAD

**Issue by aroben** [electron/libchromiumcontent#133]
create-dist used to create a zip file that contained debug symbols. This made it possible to step through Chromium code in a debugger when using a prebuilt version of libchromiumcontent. It looks like the symbols zip got removed in https://github.com/atom/libchromiumcontent/pull/98. It'd be great to bring it back.

**Comment by aroben** [comment]
Having debug symbols also improves crash backtraces.

**Comment by zcbenz** [comment]
Current symbols are generated on users' side, because libchromiumcontent now ships static libraries, and I don't think there is a way to generate debug symbols for static libraries on POSIX systems.

**Comment by aroben** [comment]
> Currently debug symbols are generated on users' side, because libchromiumcontent now ships static libraries,

On Windows, each static library gets its own PDB file generated when the static library is built. So at least for Windows a symbols zip would be useful for the static library build.

On Mac, do the debug symbols get embedded in each shared library? When we were building a single large shared library we put the symbols in a separate dSYM file.

**Comment by justintaft** [comment]
@zcbenz how would you enable symbol creation? trying to fix https://github.com/atom/electron/issues/3699  , need to break in locations where unload is fired.

**Comment by ppontes** [comment]
@aroben , as zcbenz has mentioned, debug symbols are generated when you build Electron yourself. On Mac, you can prevent them from being stripped off by passing the --keep-debug-symbols option to create-dist script. Does this option help you?

**Comment by CapOM** [comment]
Also for linux see https://github.com/electron/electron/issues/13315 I still need to cleanup my local patch and submit it

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
