### ISSUE TITLE
make it cups independent (prebuilt lib)

### ISSUE THREAD

**Issue by ShyPixie** [electron/libchromiumcontent#134]
Is there a way to make it cups independent?

I'm using Gentoo Linux x86_64, that currently don't have a package for libchromiumcontent. I install atom editor with the prebuild libchromiumcontent (yes, Linux build) but that depends on cups (yes, Common Unix Printing System) and forces me to install the net-print/cups, but I really no use this.

All other packages on my system uses the cups library as an optional dependency, but libchromiumcontent don't work without cups.

There is no way to make it optional, as the other programs?

**Comment by frankhale** [comment]
This needs more information. Are you referring to the Linux build? Are you referring to CUPS (Common Unix Printing System)? What exactly are you referring to? Is something failing for you?

**Comment by LaraCraft93** [comment]
Sorry,

I'm using Gentoo Linux x86_64, that currently don't have a package for libchromiumcontent. I install atom editor with the prebuild libchromiumcontent (yes, Linux build) but that depends on cups (yes, Common Unix Printing System) and forces me to install the net-print/cups, but I really no use this.

All other packages on my system uses the cups library as an optional dependency, but libchromiumcontent don't work without cups.

There is no way to make it optional, as the other programs?

**Comment by frankhale** [comment]
I just looked through the various build files for this project and don't see any specific references to CUPS requirement. I'd be curious about whether the actual Chrome package on Gentoo also requires CUPS? I'd say if it doesn't then it should be optional for libchromiumcontent. I did have a look through of the Atom 205 ebuild for Gentoo and did not see any specific references to CUPS as a dependency. I'm definitely curious about this. It'd probably be helpful if you posted your build results just to give some more clarification to the CUPS requirement and where exactly it's failing.

**Comment by LaraCraft93** [comment]
cups is a requirement for atom-shell ebuild (![see here](https://github.com/aegypius/overlay/blob/master/dev-util/atom-shell/atom-shell-0.22.3-r2.ebuild)) because the precompiled libchromiumcontent.so is directly linked with cups:

    $ ldd /usr/share/atom/libchromiumcontent.so | grep cups
    	libcups.so.2 => /usr/lib64/libcups.so.2 (0x00007fbf02620000)

If i uninstall cups and tries start atom editor:

    $ atom -f
    /usr/share/atom/resources/../atom: error while loading shared libraries: libcups.so.2: cannot open shared object file: No such file or directory

**Comment by frankhale** [comment]
My guess is that it's required because of the print API in Chrome. Just a guess though.

**Comment by paulcbetts** [comment]
Just install CUPS

**Comment by LaraCraft93** [comment]
@paulcbetts But I don't want cups, all other packages on my system have cups as an optional dependency, see:

    $ equery d cups
     * These packages depend on cups:
    app-emulation/wine-1.7.44 (cups ? net-print/cups[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?])
    app-text/ghostscript-gpl-9.15-r1 (cups ? >=net-print/cups-1.3.8)
    dev-util/atom-shell-0.22.3-r2 (net-print/cups)
    net-fs/samba-4.1.18 (cups ? net-print/cups)
    x11-libs/gtk+-2.24.28-r1 (cups ? >=net-print/cups-1.7.1-r2[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?])
    x11-libs/gtk+-3.14.13 (cups ? >=net-print/cups-1.2[abi_x86_32(-)?,abi_x86_64(-)?,abi_x86_x32(-)?,abi_mips_n32(-)?,abi_mips_n64(-)?,abi_mips_o32(-)?,abi_ppc_32(-)?,abi_ppc_64(-)?,abi_s390_32(-)?,abi_s390_64(-)?])


Only the atom-shell that forces me to install it. That does not sound good.

**Comment by LaraCraft93** [comment]
@paulcbetts You could use dlopen() cups instead of linking to it as is. This will get rid the dependency.

**Comment by ali** [comment]
@ShyPixie This has been previously discussed here: https://github.com/atom/libchromiumcontent/issues/60

And also here: https://code.google.com/p/chromium/issues/detail?id=148984

**Comment by ShyPixie** [comment]
@ali No need to implement a possibility of printing without the cups, only make this optional for anyone who "don't want, don't need" support printing. This does not change anything for normal users, but would give more flexibility for advanced users using source-based distributions. This completely eliminates the chrome block on this issue.

**Comment by ali** [comment]
@ShyPixie I'm not sure where you'd implement the change you're suggesting. 

It seems like if you turned off the `use_cups` flag here, this project would build chromium without CUPS support, and then Atom would lose CUPS support when it/Electron pulls down the prebuilt libchromiumcontent. I might not be understanding this correctly, though -- @zcbenz would know more.


Possibly relevant links:

* [chromium/src/build/common.gypi](https://code.google.com/p/chromium/codesearch#chromium/src/build/common.gypi&l=2030)
* [chromium/src/printing/BUILD.gn](https://code.google.com/p/chromium/codesearch#chromium/src/printing/BUILD.gn&q=use_cups&sq=package:chromium&type=cs&l=126)
* [code search for the "use_cups" flag in chromium](https://code.google.com/p/chromium/codesearch#search/&q=use_cups%20file:%5Esrc/&sq=package:chromium&type=cs)

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
