### ISSUE TITLE
Compilation fails on Windows with ffmpeg_branding set to ChromeOS

### ISSUE THREAD

**Issue by hugoatease** [electron/libchromiumcontent#152]
In order to get FLAC support in my Electron application, I'm trying to build a custom libchromiumcontent on Windows with ffmpeg_branding set to ChromeOS.

libchromium content build succeeds with default chromiumcontent.gypi, but I get the above error from yasm with the flag changed.

```
λ python script\build -t x64
ninja: Entering directory `vendor\chromium\src\out\Release_x64'
[3/2681] RULE Compile assembly libavcodec\x86\me_cmp.asm
FAILED: C:\Python27\python.exe gyp-win-tool action-wrapper environment.x64 ffmpeg_yasm_target_assemble_09ab246a
61f84f7fef6ac74dbf1e639a.284cd41d40aea3f56ebc2f880c951615.rsp ..\..\third_party\ffmpeg
yasm: FATAL: unable to open include file `config.asm'
[3/2681] RULE Compile assembly libavcodec\x86\blockdsp.asm
FAILED: C:\Python27\python.exe gyp-win-tool action-wrapper environment.x64 ffmpeg_yasm_target_assemble_09ab246a
61f84f7fef6ac74dbf1e639a.c83b91ed1e5657c043d593d8065f1f31.rsp ..\..\third_party\ffmpeg
yasm: FATAL: unable to open include file `config.asm'
[3/2681] RULE Compile assembly libavcodec\x86\h264_qpel_10bit.asm
FAILED: C:\Python27\python.exe gyp-win-tool action-wrapper environment.x64 ffmpeg_yasm_target_assemble_09ab246a
61f84f7fef6ac74dbf1e639a.09327066372c7d95c4f55f2e64192b80.rsp ..\..\third_party\ffmpeg
yasm: FATAL: unable to open include file `config.asm'
ninja: build stopped: subcommand failed.
```

Is there something I'm missing with yasm, or a way to generate the missing config.asm files ?

**Comment by ali** [comment]
@hugoatease Does this still fail for you?

**Comment by vishalup** [comment]
I am facing this issue with nw0.12.2 build?

**Comment by yocox** [comment]
Bump into the same issue T_T
How did you solve this problem?

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
