### ISSUE TITLE
Build fails on mojom_bindings_generator.py generate: error: unrecognized arguments: --java_output_directory

### ISSUE THREAD

**Issue by vulture** [electron/libchromiumcontent#186]
I've been cloning/building this repo from scratch multiple times over the past few months, and it has always worked fine -- but on a clean build today on the same machine without any changes to the machine that I know of, I'm now getting this error message:

c:\lcc2\libchromiumcontent>call python script\build -t ia32
ninja: Entering directory `vendor\chromium\src\out_32\Release'
[505/13931] ACTION Generating Mojo bindings from ../../mojo/public/interfaces/bindings/interface_control_messages.mojom ../../mojo/public/interfaces/bindings/pipe_control_messages.mojom
FAILED: c:\Program Files\Python27\python.exe gyp-win-tool action-wrapper environment.x86 mojo_interface_bindings_mojom_target_mojo_interface_bindings_mojom_mojom_bindings_generator_8d468ed6a961c24181d31e8b1555b2b8..rsp ....\third_party\mojo
usage: mojom_bindings_generator.py generate [-h] [-d DEPTH] [-o OUTPUT_DIR]
                                            [--debug_print_intermediate]
                                            [-g GENERATORS] [-I directory]
                                            [--typemap TYPEMAP]
                                            [--variant VARIANT]
                                            --bytecode_path BYTECODE_PATH
                                            filename [filename ...]
mojom_bindings_generator.py generate: error: unrecognized arguments: --java_output_directory=....\out_32\Release/java_mojo/mojo_interface_bindings_mojom/src
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "script\build", line 48, in <module>
    sys.exit(main())
  File "script\build", line 36, in main
    subprocess.check_call([NINJA, '-C', config_dir, target])
  File "c:\Program Files\Python27\lib\subprocess.py", line 504, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['c:\lcc2\libchromiumcontent\vendor\depot_tools\ninja.exe', '-C', 'vendor\chromium\src\out_32\Release', 'chromiumcontent_all']' returned non-zero exit status 1

Was there a recent change that would have required changes in the build process?

**Comment by zerocode1337** [comment]
upstairs + 1 ，please tell how to slove it，thanks～

**Comment by brenca** [comment]
I had this problem too, downgrading from python 2.7.12 to 2.7.7 solved it

**Comment by vulture** [comment]
Not all Python 2.7's are created equal. Use the Python included with google's depot_tools, and this solves it. Closing issue.
