### ISSUE TITLE
install-build-deps.sh --arm conflicts on Ubuntu 14.04.4

### ISSUE THREAD

**Issue by komcconnell** [electron/libchromiumcontent#192]
I've installed libchromiumcontent v47.0.2526.110 on my Ubuntu 14.0.4 system (under a VM).  I'm trying to cross compile for a Linux ARM embedded platform.  Following the build instructions:

  ./script/bootstrap
  ./script/update -t arm

the above works fine.  But the following fails:

  cd vendor/chromium/src
 ./build/install-build-deps.sh --arm --no-nacl

The package install of XXX results in the following error:

Selecting previously unselected package libstdc++6-armhf-cross.
Preparing to unpack .../libstdc++6-armhf-cross_4.8.4-2ubuntu1~14.04.1cross0.11.1_all.deb ...
Unpacking libstdc++6-armhf-cross (4.8.4-2ubuntu1~14.04.1cross0.11.1) ...
dpkg: error processing archive /var/cache/apt/archives/libstdc++6-armhf-cross_4.8.4-2ubuntu1~14.04.1cross0.11.1_all.deb (--unpack):
 trying to overwrite '/usr/share/gcc-4.8/python/libstdcxx/**init**.py', which is also in package libstdc++6:amd64 4.8.4-2ubuntu1~14.04.1
...
Errors were encountered while processing:
 /var/cache/apt/archives/libstdc++6-armhf-cross_4.8.4-2ubuntu1~14.04.1cross0.11.1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

At that point, the package installer is confused, and I have to start a tedious process of removing packages manually to get the installer back into usable shape.

Is this a known problem?  How do I get a clean installation?

**Comment by komcconnell** [comment]
I should mention that the above problem is building on a Macbook Pro with VMWare (Fusion 8).

**Comment by piotrekzielonka** [comment]
Saturo

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
