### ISSUE TITLE
Custom build flags?

### ISSUE THREAD

**Issue by barchard** [electron/libchromiumcontent#209]
Is it possible to build Chromium with the `enable-web-bluetooth` on to enable [Web Bluetooth](https://developers.google.com/web/updates/2015/07/interact-with-ble-devices-on-the-web?hl=en) then incorporate this into Electron? I'd like to use Bluetooth in my Electron app without the huge Node JS dependencies.

Thanks

**Comment by zcbenz** [comment]
It is not a compilation flag, you need to pass it in command line.
