### ISSUE TITLE
Chromium 53.0.2785.89 released

### ISSUE THREAD

**Issue by bbondy** [electron/libchromiumcontent#228]
Is there an update in progress already?

**Comment by zcbenz** [comment]
This release is 10 days earlier than schedule, I plan to start doing the update next week.

**Comment by bbondy** [comment]
Thanks, I noticed it's a general trend for the last several releases that they release a week early. Would be great to get on beta and have a quick rebase before release for future ones, we're willing to help.

**Comment by jbergstroem** [comment]
Think this can be closed now :)
