### ISSUE TITLE
Allow offline build

### ISSUE THREAD

**Issue by mildred** [electron/libchromiumcontent#237]
When building from a restricted environment (no network access, incorrect CA certificates), build fails. This happens for example from flatpak-builder (xdg-app).

libchromiumcontent should be able to use an already downloaded version of the chromium source tarball. And when building chromium, it should be able to do so without triggering a clang download (this happens in `vendor/chromium/src/tools/clang/scripts/update.py`) or using a tarball that was downloaded before the build.

I have a preliminary patch waiting on my computer, nothing finished yet, but it requires to patch chromium itself. Either this should go upstream, or we should be able to build without clang at all (just use the native compiler).

**Comment by zcbenz** [comment]
I suggest upstreaming the change to upstream first, maintaining patches on our side is very painful so we should not do that unless necessary. But Chromium team may just do not like it :( .

**Comment by mildred** [comment]
I agree with upstreaming as much as possible, but I will wait until I have a successful build (it takes time, and disk space, three times now I have filled up my disk with the chromium build)

**Comment by Announcement** [comment]
'tis the nature of working with chromium.
also about how much space is the chromium build taking, or the entire electron/libchromimumcontent build setup taking for you?

**Comment by cifratila** [comment]
@Announcement You should be prepared to have at least 100 GB of free space if you want to compile LIBCC

**Comment by cifratila** [comment]
@mildred Having a tar of chromium sources is not enough. If you check the `update` script for example on linux you need a sysroot image, which can of course be created locally, but you would still need to modify the sysroot scripts from inside Chromium to make them point to a location on the disk.

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
