### ISSUE TITLE
Build failing on windows

### ISSUE THREAD

**Issue by nripendra** [electron/libchromiumcontent#264]
Hi,

Building libchromiumcontent on windows fails with following error:

ninja: Entering directory `src\out\Release_x64'
[21/18748] LIB obj/base/third_party/dy...ic_annotations/dynamic_annotations.lib
FAILED: obj/base/third_party/dynamic_annotations/dynamic_annotations.lib
E:/portable-softwares/depot_tools/python276_bin/python.exe ../../build/toolchain
/win/tool_wrapper.py link-wrapper environment.x64 False lib.exe /nologo /ignore:
4221 /OUT:obj/base/third_party/dynamic_annotations/dynamic_annotations.lib @obj/
base/third_party/dynamic_annotations/dynamic_annotations.lib.rsp
Microsoft (R) Library Manager Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.

**LINK : fatal error LNK1171: unable to load mspdbcore.dll (error code: 127)**
[26/18748] CXX obj/base/base_paths/base_paths_win.obj
ninja: build stopped: subcommand failed.

Update:
I'm building with "-c shared_library" option

**Comment by cifratila** [comment]
@nripendra What version are you trying to build?

I am able to build latest libchromiumcontent on my Windows 10 machine.

Do you have all the pre-requisites from here: [Build Instructions Windows](https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md) ?

**Comment by nripendra** [comment]
@cifratila 
It looks like there is some problem in my vc installation. The problem occurs when compiling using VC/bin/amd64/lib.exe. This problem doesn't occur when using lib.exe from VC/bin.

Closing this issue.
