### ISSUE TITLE
electron doesn't depend on libffmpeg anymore

### ISSUE THREAD

**Issue by Kagami** [electron/libchromiumcontent#268]
Hi.

Seems like electron binaries since `1.4.15` don't depend on libffmpeg anymore, at least on 64-bit Linux:

```
$ npm i electron@1.4.15
$ nm -D node_modules/electron/dist/electron | grep av_buffer_create
                 U av_buffer_create
$ readelf -d node_modules/electron/dist/electron | grep libffmpeg  
 0x0000000000000001 (NEEDED)             Shared library: [libffmpeg.so]

$ npm i electron@1.6.3
$ nm -D node_modules/electron/dist/electron | grep av_buffer_create
00000000032b29e0 T av_buffer_create
$ readelf -d node_modules/electron/dist/electron | grep libffmpeg
<empty>
```

Is this correct?

I find it kinda wrong because:

1. You still ship `libffmpeg.so` which weight 3 megabytes and isn't used.
2. It's not possible to use your own version of `libffmpeg` anymore, e.g. without proprietary codecs. (At least without recompilation.)
3. You still provide separate `ffmpeg` packages which makes no sense.

**Comment by poiru** [comment]
I was actually wondering why e.g. electron-v1.6.0-darwin-x64.zip is about 2MB larger than electron-v1.5.1-darwin-x64.zip. This might explain it!

**Comment by Kagami** [comment]
I think I actually like the new behavior more. But still curious about details of that change.

**Comment by MarshallOfSound** [comment]
> I think I actually like the new behavior more

@Kagami Just so we don't go down that path, the new behavior is worse.  People need to have the choice to not use the FFMPEG with prop codecs 👍 

/cc @zcbenz Ideas on where this happened, assuming it was part of the gyp -> gn transition.

**Comment by paulcbetts** [comment]
I suspect ffmpeg is loaded dynamically, so that if it's not present libcc can fall back and just say "sry, can't play the video"

**Comment by Kagami** [comment]
No, `T` symbols mean they are exported by the binary.

**Comment by zcbenz** [comment]
This is a side effect of the gn update, libffmpeg is now built as part of Electron instead of being linked as shared library. This is a bug.
