### ISSUE TITLE
Not all PDB files are included in the distribution

### ISSUE THREAD

**Issue by zcbenz** [electron/libchromiumcontent#287]
This is to note an issue with PDB files on Windows.

With the switch to use gn, PDB files now have short file names like `base_cc.pdb` and `stub_cc.pdb`, and since the generated `.lib` files include object file from multiple libraries, one generated `.lib` may include multiple PDB files with same names.

In order to make PDB files work with debugger, they have to be placed within the same directory with the corresponding `.lib` file, so PDB files with same names will be overwritten. And because paths to PDB files are hardcoded in object files, we can not rename them after they are generated.

In the end certain PDB files are missing when building Electron, it might affected debugging, and triggers lots of warnings in the linking stage.

One way to fix this is to make gn include paths in the generated PDB file name, so `base_cc.pdb` becomes `ui_base_base_cc.pdb` and `base_base_cc.pdb`. However I can't find a way to do that, in the toolchain configuration only expansions can be used in variables, I don't know how to dynamically change the name, anyone interested in solving this can take a look at:
https://cs.chromium.org/chromium/src/build/toolchain/win/BUILD.gn?type=cs$&l=155

**Comment by zcbenz** [comment]
@juturu The PDB files are in their own sub directories so adding them manually to debugger would be extremely tedious, and I'm not sure if even that's possible.

Or you can build libcc on your own machine and then build electron with it, the paths to PDBs are hardcoded in object files so debugger should be able to find the correct PDB files. (I haven't tried this though)

**Comment by alexeykuzmin** [comment]
> Or you can build libcc on your own machine and then build electron with it, the paths to PDBs are hardcoded in object files so debugger should be able to find the correct PDB files. (I haven't tried this though)

It should work. I see no linking warnings when I build Electron with locally built libcc.

**Comment by enlight** [comment]
I've figured out a way to prefix the PDB names with a path as suggested by @zcbenz (`obj/ui/base/base_cc.pdb` -> `obj/ui/base/obj_ui_base_base_cc.pdb`), this is done before invoking the compiler. I've still got a bunch of testing to do though.

**Comment by alespergl** [comment]
This discussion is apparently only about the static library (aka release) build.

It is known that in that build we don't use the `.lib` files produced by gn targets, but create our own by assembling various objects files, which are not necessarily the same set as the ones which go into the regular gn target `.lib` files. The discussed `.pdb` files which you're attempting to distribute correspond to the regular gn targets, not our `.lib`s.

I therefore see it as sub-optimal (although it might work) to try to collect these PDBs and use them. Wouldn't it be better to do something along the lines mentioned in [this SO response](https://stackoverflow.com/a/7575545)? I.e. include the debugging information in the object files and that way have it also embedded in the `.lib`s we create for Electron? Then the symbols would presumably be transferred to `node.dll.pdb` produced at link time and no extra PDBs would be necessary.

**Comment by enlight** [comment]
I've opened PR #338 to patch the build toolchain to rename PDBs. I like the sound of @alespergl suggestion, however the docs for `/Z7` do mention this:

>For distributors of third-party libraries, there is an advantage to not having a .pdb file. **However, the .obj files for the precompiled headers are necessary during the link phase, and debugging.** If there is only type information (and no code) in the .pch object files, you will also have to compile with /Yl (Inject PCH Reference for Debug Library).

I guess there's only one way to find out if it'll work or not :)

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
