### ISSUE TITLE
script/update fails on a clean Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/libchromiumcontent#320]
The problem is that the update script doesn't install build dependencies.
They're supposed to be [installed](https://chromium.googlesource.com/chromium/src/+/lkcr/docs/linux_build_instructions.md#Install-additional-build-dependencies) right after the Chromium code is checkout out, before `gn gen` is run.

So right now steps to build libcc on linux look like this:
1. `./script/bootstrap` [succeeds]
2. `./script/update` [fails]
3. `./src/build/install-build-deps.sh` [succeeds]
4. `./script/update` [succeeds]
5. `./script/build`

/cc @kevinsawicki

**Comment by cifratila** [comment]
@alexeykuzmin I would rather offer the user option to install build deps, you anyways need to run the `install-build-deps.sh` using `sudo`

Wouldn't like to see `sudo ./script/update` which will even mess up the access rights.

Plus if you check: [Build Pre-Requisites](https://github.com/electron/libchromiumcontent/blob/master/README.md#prerequisites) there are links to what you need to do before trying to build your own LIBCC.

**Comment by zcbenz** [comment]
Having the `bootstrap` script asking for root permission is quite scary, I don't know any project doing that. There is probably no perfect solution, Chromium's bootstrapping script set up almost everything, but they still left out the part of installing build dependencies.

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
