### ISSUE TITLE
Add indexes to patch files

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/libchromiumcontent#339]
```
accelerator.patch       →    0001-accelerator.patch
allow_new_privs.patch   →    0002-allow_new_privs.patch
...
```

I will allow us to always add new patches to the end of the list.

I guess we should do it only after the Ch59 branch is merged to avoid delays.
Renames will cause conflicts in the Ch61 branch, but I don't think it's a big deal.

/cc @tonyganch

**Comment by zeke** [comment]
Do these indexes need to be added by file date or name or anything?

**Comment by MarshallOfSound** [comment]
@zeke Just in order the patches were created, patches are applied in alphabetical order so doing this enforces an order while allowing us to name them correctly (instead of coming up with a patch name that just happens fits in the right slot alphabetically) 😆

**Comment by alexeykuzmin** [comment]
@zcbenz can it lead any undesirable side effects?

**Comment by zcbenz** [comment]
> @zcbenz can it lead to any undesirable side effects?

I don't think it would have undesirable side effects.

Having multiple patches modifying one file makes it very hard to update the patches for Chrome updates, you have to generate diffs carefully in right sequence and it is definitely not an easy task.

In the past I just avoided it at all, when a new patch was modifying a file already patched, I would merge the patch into other patches, or create a new patch that have all the changes to one file.

**Comment by alexeykuzmin** [comment]
> Having multiple patches modifying one file makes it very hard to update the patches for Chrome updates, you have to generate diffs carefully in right sequence and it is definitely not an easy task.

It should be much easier now since we use actual Chromium repo and not a snapshot.

**Comment by zcbenz** [comment]
> It should be much easier now since we use actual Chromium repo and not a snapshot.

It is still very frustrating, however if you are fine with it then I'm totally OK with this approach, since it is you doing the heavy update now 😄 .
