### ISSUE TITLE
how to compile libchromiumcontent on other platform.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [electron/libchromiumcontent#351]
I want to cross compile libchromiumcontent on mips64el(loongson 3a) cpu. but I can't find any infomation to do this. Is there any good way to do it?

**Comment by alexeykuzmin** [comment]
libchromiumcontent is basically just Chromium, so the best way to get an answer is to check Chromium build docs.

See https://www.chromium.org/developers/gn-build-configuration:
> Possible values for the `target_cpu`:
> <...>
> - If you specify an Android build (see below) the default CPU architecture will be "arm". You could try overriding it to "arm64", "x86", "mipsel", or "mips64el" but the GN builds for these aren't regularly tested.

**Comment by alexeykuzmin** [comment]
@MiyamuraMiyako check this – #364
Can we close this issue now?

**Comment by MiyamuraMiyako** [comment]
@alexeykuzmin Yes.I will close it :)
