### ISSUE TITLE
libchromiumcontent build on electron v1.7.7 fails

### ISSUE THREAD

**Issue by mailtokartik1** [electron/libchromiumcontent#354]
Electron version: 1.7.7
Operating System: windows x64

The manual build of libcc in electron v17.7 fails. The command used is `python script/bootstrap.py -v --build_libchromiumcontent`. It worked fine with the other electron versions but the manual build fails with the  v1.7.6 and v1.7.7.
`

**Comment by cifratila** [comment]
@mailtokartik1 
More info would be great, what is the exact error?

**Comment by mailtokartik1** [comment]
![screenshot 38](https://user-images.githubusercontent.com/29715398/30627130-08296c1c-9dec-11e7-99a3-9c86cc0c52f4.png)

This is where the build fails. Ask me for more traces if required but I guess this will be enough

**Comment by anupam** [comment]
I think there is some path issue here, i tried debugging but couldn't find, it seems the gclient config files can't be found although it is there. Can some one take a look at this?

**Comment by anupam** [comment]
anyone got this to work?

**Comment by mailtokartik1** [comment]
I have tried removing the windows 260 character limit but that did not seem to work as well.

**Comment by anupam** [comment]
Got the latest from master and no longer seeing this error.

**Comment by mailtokartik1** [comment]
Did you use version 1.7.7?

**Comment by anupam** [comment]
No v 1.8.1

**Comment by mailtokartik1** [comment]
yeah the build fails on v1.7.7 thats the point

**Comment by mailtokartik1** [comment]
The build fails with v1.7.9 and the command is non-existent in v1.8.1. Can you tell me the command you used?

**Comment by alexeykuzmin** [comment]
> the command is non-existent in v1.8.1

@mailtokartik1 
`--build_libchromiumcontent` was renamed to `--build_release_libcc` in #10253

**Comment by mailtokartik1** [comment]
@alexeykuzmin  thanks. It works now.
