### ISSUE TITLE
Run Chromium tests

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/libchromiumcontent#360]
Big stuff. The plan is:

- [ ] Identify all test "suites" that cover the code we use from Chromium (i.e. content_unittests, etc.)
- [ ] List failing tests from all "suites"
- [ ] Fix failing tests (either modify related code in a patch or modify/disable the test)
- [ ] _optional_ Add tests for patches we have
- [ ] Build and run tests on CI bots

Chromium tests documentation:
- [Running tests locally](https://www.chromium.org/developers/testing/running-tests)
- [Layout Tests](https://chromium.googlesource.com/chromium/src/+/master/docs/testing/layout_tests.md#running-the-tests)

Related PRs: #440, #441, #443

/cc @jkleinsc, @tonyganch, @zcbenz, @groundwater, @gavignus

**Comment by alexeykuzmin** [comment]
We can start with the `content_unittests` and go directly to the step five: "Build and run tests on CI bots." It means we need to 1) build `content_unittests` target, 2) run it, 3) parse results, 4) display results in a human-readable form.

@jkleinsc I would need your help to actually run the tests on CI machines.
Not right now, but in the nearest future.

**Comment by alexeykuzmin** [comment]
Build config for tests:

```
is_debug = false
is_component_build = true
dcheck_always_on = true
symbol_level = 1
compute_grit_inputs_for_analyze = true
enable_update_channel = false
enable_nacl = false
```

**Comment by alexeykuzmin** [comment]
### Failing tests

#### content_unittests
- DOMStorageMapTest.EnforcesQuota

**Comment by jkleinsc** [comment]
@alexeykuzmin is there any thought about running Electron test suite as well?  In theory we can build Electron from the compiled libcc and run the Electron test suite.  I think maybe all the parts are there because on the Electron build you can specify where libcc is.

**Comment by alexeykuzmin** [comment]
@jkleinsc so you're suggestion on every change in libcc run
build libcc → run libcc tests → build Electron (with this libcc) → run Electron tests ?
Makes a lot of sense.

It would require some non-trivial changes in out CI setup though. But will be extremely useful.

**Comment by jkleinsc** [comment]
Yes, that way we verify libcc PR is ok to go without having to have electron PR before we can verify it.

**Comment by alexeykuzmin** [comment]
Ok. So, on every commit in the _libcc_ repo we should trigger _not libcc_, but _Electron_ build.
Electron builds shouldn't expect libcc binaries to be always available for download, but instead
a) trigger a libcc build, if that libcc revision has never been built
b) wait for the libcc build, if there is a build in progress
c) fail if the libcc build has failed

Can we setup builds like that on all our CI platforms?

**Comment by jkleinsc** [comment]
@alexeykuzmin a couple of thoughts
1. Why can't we build libcc from Electron if commit doesn't exist?  I know it means Electron build could potentially run super long, but that should be the exception not the norm.   The nice thing about this would be we could make sure that libcc is being tested against the version of Electron it is intended for and would cover the case where there are changes to both libcc and electron.  Maybe we could throw something in a config file that tells the CI build to build libcc if it isn't already built?

2. If we are going to build Electron from a libcc PR, it would be my preference to build libcc first and then point Electron to the newly compiled build.  As far as which Electron to build, we could derive it from target branch name or possibly use some config file to specify which Electron branch.

**Comment by alexeykuzmin** [comment]
> Why can't we build libcc from Electron if commit doesn't exist? 

I'm afraid I don't fully understand what you mean by "commit doesn't exist" )

> As far as which Electron to build, we could derive it from target branch name or possibly use some config file to specify which Electron branch.

Or we can simply build it against _master_, at least for now. We can add more complex logic later.

**Comment by jkleinsc** [comment]
@alexeykuzmin sorry I meant if libcc for a specific commit hasn't been build.

Building against master is a good start!

**Comment by alexeykuzmin** [comment]
> I meant if libcc for a specific commit hasn't been build

Sure, of course we can build libcc as part of Electron build. We even have this option already implemented in the Electron build scripts.

But maybe it would make sense _to trigger_ a libcc build from an Electron build _and wait_ for it to finish, instead of building everything in place? Having libcc binaries available for download could save us some time if we would have to restart a build.

**Comment by alexeykuzmin** [comment]
@jkleinsc 
My idea was to trigger Electron builds for all PRs in _both_  libcc and Electron repos.
For Electron PRs run builds as usual, for libcc – run (Electron master + new libcc).
I don't know if it is possible or even make sense )

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
