### ISSUE TITLE
libchromiumcontent MIPS64 Support

### ISSUE THREAD

**Issue by ClarkWang-2013** [electron/libchromiumcontent#362]
I recently completed the libchromiumcontent build on Loongson(MIPS64EL) platform.

Build libchromiumcontent follow the steps below:
$ ./script/bootstrap
$ ./script/update -t mips64el
$ ./script/build -t mips64el
$ ./script/create-dist -t mips64el

And generate files as follows:
libchromiumcontent-static.zip libchromiumcontent.zip dist/main/

I would like to ask how do put my patch push into your project libchromiumcontent?

**Comment by zcbenz** [comment]
@ClarkWang-2013 It sounds awesome! You can create a pull request for your changes.

**Comment by ClarkWang-2013** [comment]
#364

**Comment by codebytere** [comment]
Closing as PR is merged.
