### ISSUE TITLE
Subpixel font rendering with freetype 2.8.1

### ISSUE THREAD

**Issue by kolya-ay** [electron/libchromiumcontent#384]
With updated libfreetype fonts look "dirty" and painful to read due background artifacts. Here is a screenshot from unmodified `electron-quick-start`:

![spectacle h23809](https://user-images.githubusercontent.com/238048/32491240-0c5c2f12-c3c7-11e7-8a43-3ded1c79e4a7.png)

The issue affects all the Linux users with new version of the library. See: atom/atom#15737, Microsoft/vscode#35675.

It seems to be [upstream Skia issue](https://bugs.chromium.org/p/skia/issues/detail?id=6663). The fix could probably be backported from newer Chromium versions.

**Comment by MarshallOfSound** [comment]
Backporting the Skia patch to fix this:

* `1.6.x`: https://github.com/electron/libchromiumcontent/pull/386
* `1.7.x`: https://github.com/electron/libchromiumcontent/pull/385
* `1.8.x`: *Coming Soon*

**Comment by bhack** [comment]
I hope that could be backported also on different Electron releases.

**Comment by bhack** [comment]
A PR for 1.6.x is available https://github.com/electron/libchromiumcontent/pull/386

**Comment by zeflap** [comment]
Still broken on freetype 2.8.1

**Comment by ExecutorElassus** [comment]
I'd suggest modifying the title to "freetype >2.8", as this is also broken when using freetype-2.9. Incidentally, though I use electron-1.6, this is still broken on my system; is this part of the regular electron release, or do I need to patch manually?

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
