### ISSUE TITLE
Two different patches have the same sequence number

### ISSUE THREAD

**Issue by ahmedmohamedali** [electron/libchromiumcontent#390]
Hi libchromiumcontent team,

This issue is just to let you know the following patches have both the sequence number 042.

*patches/042-high-sierra-nvidia-gpu.patch* (https://github.com/electron/libchromiumcontent/commit/b19b4d400da9721bbf662613e78515d26268cc53)

*patches/042-webui_in_subframes.patch* (https://github.com/electron/libchromiumcontent/commit/fe6086f95666ec94cab1050a012031ca6a7811f1)

Thanks.

**Comment by alexeykuzmin** [comment]
@ahmedmohamedali `patches/042-high-sierra-nvidia-gpu.patch` is already removed
Thanks!
