### ISSUE TITLE
Windows 64 build fails with following error

### ISSUE THREAD

**Issue by anupam** [electron/libchromiumcontent#414]
`C:\Users\denimuser\playground\libchromiumcontent>python script\build -R -t x64
ninja: Entering directory 'src\out-x64\static_library'
[15290/19718] CXX obj/third_party/WebKit/Source/core/core_generated/LocalWindowProxy.obj
FAILED: obj/third_party/WebKit/Source/core/core_generated/LocalWindowProxy.obj
C:/depot_tools/win_tools-2_7_6_bin/python/bin/python.exe ../../build/toolchain/win/tool_wrapper.py cl-wrapper ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64/cl.exe" /nologo /showIncludes /FC @obj/third_party/WebKit/Source/core/core_generated/LocalWindowProxy.obj.rsp /c ../../third_party/WebKit/Source/bindings/core/v8/LocalWindowProxy.cpp /Foobj/third_party/WebKit/Source/core/core_generated/LocalWindowProxy.obj obj/third_party/WebKit/Source/core "core_generated_cc.pdb"
c:\users\denimuser\playground\libchromiumcontent\src\third_party\webkit\source\bindings\core\v8\localwindowproxy.cpp(127): error C3861: 'installConditionalFeaturesOnWindow': identifier not found
[15299/19718] CXX obj/third_party/WebKit/Source/bindings/core/v8/bindings_core_impl/V8GeneratedCoreBindings.obj
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "script\build", line 61, in <module>
    sys.exit(main())
  File "script\build", line 45, in main
    subprocess.check_call([NINJA, '-C', os.path.relpath(out_dir), target], env=env)
  File "C:\depot_tools\win_tools-2_7_6_bin\python\bin\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\denimuser\\playground\\libchromiumcontent\\vendor\\depot_tools\\ninja.exe', '-C', 'src\\out-x64\\static_library', 'chromiumcontent:chromiumcontent']' returned non-zero exit status 1`

I am trying to build electron version 1.7.9 checked out commit 62a432e for libchromiumcontent. 
Thanks,
Anupam

**Comment by anupam** [comment]
Is there any tag or branch which I should be using to build libchromiumcontent ?

**Comment by alexeykuzmin** [comment]
@anupam You should be able to build from any revision in master.
Just make sure that you set up the environment correctly.
https://chromium.googlesource.com/chromium/src/+/61.0.3163.100/docs/windows_build_instructions.md#System-requirements

**Comment by alexeykuzmin** [comment]
I'm going to close the issue since everything works fine on our CI machines.
