### ISSUE TITLE
Cannot use touch keyboard with password fields

### ISSUE THREAD

**Issue by conteit** [electron/libchromiumcontent#641]
See main issue at https://github.com/electron/electron/issues/13832 for details

It looks like the main Chromium project is already working on the fix for this problem, caused by a breaking change in Windows 10 1803 (https://chromium-review.googlesource.com/c/chromium/src/+/946928). 

I've tried to backport it, but it looks like the patch refers to a new feature that has been introduced after the version currently embedded in Electron.

**Comment by MarshallOfSound** [comment]
@conteit This should live over in electron/electron#13832, if someone gets some free time to tackle that patch they can look at it.
