### ISSUE TITLE
Shift modifier in accelerator is not displayed in menu

### ISSUE THREAD

**Issue by katrinalui** [electron/libchromiumcontent#679]
We recently updated to Electron v3.0.0-beta.8 from v2.0.5 and noticed that accelerators with the Shift modifier are missing the "Shift" part when displayed in the app menu in Windows (pretty much the exact same bug in this [closed issue](https://github.com/electron/electron/issues/11429)). For example, the accelerator `CmdOrCtrl+Shift+N` will show up as `Ctrl+N` on Windows, although pressing `Ctrl+Shift+N` functions as expected .

This issue was previously fixed in https://github.com/electron/libchromiumcontent/pull/430.

**Comment by MarshallOfSound** [comment]
Hey @katrinalui can you raise this over on `electron/electron` so we can triage it as an Electron issue correctly 👍
