### ISSUE TITLE
Linux video acceleration support behind a flag

### ISSUE THREAD

**Issue by mgcrea** [electron/libchromiumcontent#92]
Would it be possible for atom-shell to bypass existing protections in chromium preventing hardware video decode on intel chipset with linux? The idea would be to implement this chromium ticket [Issue 176883018: Remove additional protection of kDisableAcceleratedVideoDecode in bpf_gpu_policy_linux.cc.](https://codereview.chromium.org/176883018) that has been closed for the [sake of stability](https://codereview.chromium.org/176883018/#msg6).

That would be a great addition for linux app builders out there.

Some more context: [Video Acceleration Takes The Backseat On Chrome For Linux](http://www.phoronix.com/scan.php?page=news_item&px=MTYyMDk)

Related atom-shell issue: https://github.com/atom/atom-shell/issues/1032

**Comment by mgcrea** [comment]
Reading [LinuxHWVideoDecode](https://code.google.com/p/chromium/wiki/LinuxHWVideoDecode), it looks like the only required step to turn it on would be:

> Add to $GYP_DEFINES:
chromeos=1 to link in VaapiVideoDecodeAccelerator
proprietary_codecs=1 ffmpeg_branding=Chrome to allow Chrome to play h.264 content, which is the only codec VAVDA knows about today.

The workaround solution for now is to use [this ppa](https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-beta) instead of atom-shell, which enables hardware acceleration and works as a charm.

**Comment by mgcrea** [comment]
@zcbenz any news regarding this? Would you consider merging a PR addressing this?

**Comment by zcbenz** [comment]
@mgcrea Yeah I will accept a PR on this, though as far as I can see the patch you pasted above has already been applied in Chromium.

**Comment by maximbaz** [comment]
There's a [chromium-vaapi](https://aur.archlinux.org/packages/chromium-vaapi/) package for ArchLinux, which enables the hardware acceleration for Intel chipsets. I've been using it for weeks, works perfectly.

@zcbenz would it be possible to just take the [vaapi patch](https://aur.archlinux.org/cgit/aur.git/tree/vaapi_patch_r2.patch?h=chromium-vaapi) from there and put in this repo among other patches?

The [full build script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=chromium-vaapi) includes other patches as well, but I think they are doing something else.

Although, that patch is based on the recent stable Chromium v59, so perhaps this should go after https://github.com/electron/libchromiumcontent/pull/313.

**Comment by bhack** [comment]
Some upstream progress https://chromium-review.googlesource.com/c/chromium/src/+/532294

**Comment by freechelmi** [comment]
[Off-topic] We still don't understand why the google team needs 6 years to accept a bloody flag for linux GPU decode where every other platforms have it enabled as default.

**Comment by bhack** [comment]
Firefox status isn't better https://bugzilla.mozilla.org/show_bug.cgi?id=1210727

**Comment by maximbaz** [comment]
The upstream patch mentioned above works very well, reportedly enabling support not only for Intel hardware, but for other GPUs as well. It requires enabling a few chrome flags after that, e.g. these work very well for me:

```
--enable-accelerated-mjpeg-decode
--enable-accelerated-video
--enable-gpu-rasterization
--enable-native-gpu-memory-buffers
--ignore-gpu-blacklist
```

Can we not wait on upstream and just use that patch and enable the flags in electron?

**Comment by sebakerckhof** [comment]
This is now by default in chromium on fedora: https://src.fedoraproject.org/rpms/chromium/c/278c62709d1dba5883c3b69047706837bb402bd7?branch=master

and ubuntu and arch linux is also looking into it:
https://www.linuxuprising.com/2019/01/ubuntu-testing-chromium-snap-with-vaapi.html
https://bbs.archlinux.org/viewtopic.php?pid=1830639

**Comment by max-baz** [comment]
~Arch Linux also includes the patch since February, enabled by default 😉~

Sadly, [not anymore](https://bbs.archlinux.org/viewtopic.php?pid=1837037#p1837037).

**Comment by MarshallOfSound** [comment]
Hey there,

It's been a long time coming but the `libchromiumcontent` repository is being archived as it is no longer used in the Electron build system (🎉 this is a good thing).

If your issue is still relevant to Electron in it's current build system (please verify first) then you should probably raise a similar issue on `electron/electron`.

Thanks 😄
